<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('DWS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <header>
            HEADER<br/>
            <?php echo $this->leagueheader($this->league); ?>
        </header>
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <?php
                    //echo $this->notifications();
                    echo $this->partial('layout/partials/flashmessages');
                    $sidebarAvailable = false;
                    ?>
                    <?php if ($this->progress) : 
                        $sidebarAvailable = true;
                    ?>
                    <div class="sidebar">
                        Sidebar
                        <?php echo $this->sidebarprogress($this->progress); ?>
                    </div>
                    <?php endif; ?>
                    <div class="main-content <?php if ($sidebarAvailable === false) { echo 'without-sidebar'; } ?>">
                        <div class="sidebar"></div>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
